import { cn } from "@/utils";
import { Link } from "react-router-dom";

export const Home = () => {
	return (
		<>
			<main className="flex h-screen w-screen flex-col items-center justify-center bg-zinc-100 font-serif">
				<h1 className="mb-4 text-5xl text-zinc-800">
					Welcome to Chaos Vite React Template
				</h1>
				<p className="text-base text-zinc-700">
					This is the default page generated by Chaos-cli which mean to offer
					you a project out of the box.
				</p>
				<p className="mt-4 text-2xl">Enjoy your development!</p>
				<p className="">
					Get started by editing&nbsp;
					<code className="rounded bg-zinc-300 p-1 font-mono font-bold">
						src/pages/Home.tsx
					</code>
				</p>
				<div className="mt-4 rounded bg-zinc-500 p-1">
					<Link to="/test">go to test page</Link>
				</div>
			</main>
			<div className={`${cn({ ["rounded"]: false })}`}></div>
		</>
	);
};
